stages:
  data_ingestion:
    cmd: python3 src/Model/pipeline/stage_01_data_ingestion.py
    deps:
      - src/Model/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/data.zip

  data_validation:
    cmd: python3 src/Model/pipeline/stage_02_data_validation.py
    deps:
      - src/Model/pipeline/stage_02_data_validation.py
      - config/config.yaml
    outs:
      - artifacts/data_validation/status.txt

  data_transformation:
    cmd: python3 src/Model/pipeline/stage_03_data_transformation.py
    deps:
      - src/Model/pipeline/stage_03_data_transformation.py
      - config/config.yaml
    outs:
      - artifacts/data_transformation/train.csv
      - artifacts/data_transformation/test.csv

  model_trainer:
    cmd: python3 src/Model/pipeline/stage_04_model_trainer.py
    deps:
      - src/Model/pipeline/stage_04_model_trainer.py
      - config/config.yaml
    outs:
      - artifacts/model_trainer/model.joblib

  model_evaluation:
    cmd: python3 src/Model/pipeline/stage_05_model_evaluation.py
    deps:
      - src/Model/pipeline/stage_05_model_evaluation.py
      - src/Model/components/model_evaluation.py
      - config/config.yaml
    outs:
      - artifacts/model_evaluation/metrics.json